//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApolloConfig) DeepCopyInto(out *ApolloConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApolloConfig.
func (in *ApolloConfig) DeepCopy() *ApolloConfig {
	if in == nil {
		return nil
	}
	out := new(ApolloConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApolloConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApolloConfigList) DeepCopyInto(out *ApolloConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApolloConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApolloConfigList.
func (in *ApolloConfigList) DeepCopy() *ApolloConfigList {
	if in == nil {
		return nil
	}
	out := new(ApolloConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApolloConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApolloConfigServer) DeepCopyInto(out *ApolloConfigServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApolloConfigServer.
func (in *ApolloConfigServer) DeepCopy() *ApolloConfigServer {
	if in == nil {
		return nil
	}
	out := new(ApolloConfigServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApolloConfigServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApolloConfigServerList) DeepCopyInto(out *ApolloConfigServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApolloConfigServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApolloConfigServerList.
func (in *ApolloConfigServerList) DeepCopy() *ApolloConfigServerList {
	if in == nil {
		return nil
	}
	out := new(ApolloConfigServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApolloConfigServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApolloConfigServerSpec) DeepCopyInto(out *ApolloConfigServerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApolloConfigServerSpec.
func (in *ApolloConfigServerSpec) DeepCopy() *ApolloConfigServerSpec {
	if in == nil {
		return nil
	}
	out := new(ApolloConfigServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApolloConfigServerStatus) DeepCopyInto(out *ApolloConfigServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApolloConfigServerStatus.
func (in *ApolloConfigServerStatus) DeepCopy() *ApolloConfigServerStatus {
	if in == nil {
		return nil
	}
	out := new(ApolloConfigServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApolloConfigSpec) DeepCopyInto(out *ApolloConfigSpec) {
	*out = *in
	out.Apollo = in.Apollo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApolloConfigSpec.
func (in *ApolloConfigSpec) DeepCopy() *ApolloConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ApolloConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApolloConfigStatus) DeepCopyInto(out *ApolloConfigStatus) {
	*out = *in
	in.LastSyncedSuccess.DeepCopyInto(&out.LastSyncedSuccess)
	in.UpdateAt.DeepCopyInto(&out.UpdateAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApolloConfigStatus.
func (in *ApolloConfigStatus) DeepCopy() *ApolloConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ApolloConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}
