# This rule is not used by the project apollo-configmap itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apollo.adamswanglin.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: apollo-configmap
    app.kubernetes.io/managed-by: kustomize
  name: apolloconfigserver-viewer-role
rules:
- apiGroups:
  - apollo.adamswanglin.com
  resources:
  - apolloconfigservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apollo.adamswanglin.com
  resources:
  - apolloconfigservers/status
  verbs:
  - get
