{
 "title": "Custom-Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "apollo_config_count (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "apollo_config_count" }
   ]
  },
  {
   "title": "http_requests_total (counter)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, pod)"
    }
   ]
  },
  {
   "title": "http_request_duration_seconds_bucket (histogram)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(instance, le) (rate(http_request_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])))"
    }
   ]
  }
 ]
}